//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDCG.App.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TxtResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TxtResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestDCG.App.Resources.TxtResource", typeof(TxtResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confiramar.
        /// </summary>
        public static string BtnConfirm {
            get {
                return ResourceManager.GetString("BtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string BtnLogOut {
            get {
                return ResourceManager.GetString("BtnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus datos registrados.
        /// </summary>
        public static string LabeDataInfo {
            get {
                return ResourceManager.GetString("LabeDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor confirma tu información:.
        /// </summary>
        public static string LabeInfoTitle {
            get {
                return ResourceManager.GetString("LabeInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu dirección:.
        /// </summary>
        public static string LabeIntoInfo {
            get {
                return ResourceManager.GetString("LabeIntoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        public static string LabelDep {
            get {
                return ResourceManager.GetString("LabelDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        public static string LabelMun {
            get {
                return ResourceManager.GetString("LabelMun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LabelPss {
            get {
                return ResourceManager.GetString("LabelPss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso.
        /// </summary>
        public static string LabelTitleLogin {
            get {
                return ResourceManager.GetString("LabelTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string LabelUser {
            get {
                return ResourceManager.GetString("LabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted es el usuario {0}.
        /// </summary>
        public static string LabeTxtInfo {
            get {
                return ResourceManager.GetString("LabeTxtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string LabeWelcome {
            get {
                return ResourceManager.GetString("LabeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu dirección: (Calle/Número/Apto).
        /// </summary>
        public static string PhAddress {
            get {
                return ResourceManager.GetString("PhAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione....
        /// </summary>
        public static string PhPiker {
            get {
                return ResourceManager.GetString("PhPiker", resourceCulture);
            }
        }
    }
}
